### ISSUE TITLE
KDE/Kinoite Night Color Broken

### ISSUE THREAD

**Issue by Gyromancer** [ublue-os/nvidia#128]
Hey folks, I recently rebased from regular Kinoite to ublue-Kinoite upon switching to a Nvidia GPU. Everything seems to work so far, except KDE's Night Color feature doesn't appear to change the color temperature as it should. Is this a known issue and is there a fix? Thanks.

**Comment by akdev1l** [comment]
Known issue nvidia driver doesn't support GAMMA_LUT. Nvidia needs to fix it

**Comment by akdev1l** [comment]
ref: https://github.com/NVIDIA/open-gpu-kernel-modules/issues/162
