### ISSUE TITLE
Kinoite/KDE support?

### ISSUE THREAD

**Issue by EinoHR** [ublue-os/nvidia#21]
Would it be possible to have a Kinoite-based version of this image?
I already tried my hand at it here https://github.com/EinoHR/fedora-kinoite-nvidia, just by changing the BASE_IMAGE. That did not work, as it started spitting out errors that I can't decipher in the build image task around the second FROM (line 60 of containerfile).

If you do not want to add _official support_ for Kinoite+Nvidia images, I'd be interested in knowing what this repository's _rather long_ containerfile does differently/better when compared to just having one that enables RPMFusion and installs Nvidia drivers [as shown here](https://docs.fedoraproject.org/en-US/fedora-kinoite/troubleshooting/#_using_nvidia_drivers).

**Comment by sihawken** [comment]
Just changing the base image should work, I do it here. If you want to try your hand at it, take a look at my containerfile.
[Kinoite](https://github.com/sihawken/kinoite-msi-stealth-15m/blob/main/Containerfile)

**Comment by castrojo** [comment]
We're currently in the process of figuring out how to matrix out builds so that we can make one for each desktop, but it takes time. 

Or if you know someone who's done it before and knows GitHub actions and want to ask them to help out, that might help too. :)

**Comment by joshua-stone** [comment]
@EinoHR A local build using `quay.io/fedora-ostree-desktops/kinoite` as the base image appears to work. Did you generate your own keys?

**Comment by EinoHR** [comment]
> @EinoHR A local build using `quay.io/fedora-ostree-desktops/kinoite` as the base image appears to work. Did you generate your own keys?

I generated my own keys yesterday, but attempted a cloud build using Github actions, which kept on failing. I'm not quite sure where to upload the private key. I added it to the github "Repository secrets" with the name "COSIGN_PRIVATE_KEY".

**Comment by EinoHR** [comment]
> We're currently in the process of figuring out how to matrix out builds so that we can make one for each desktop, but it takes time.
> 
> Or if you know someone who's done it before and knows GitHub actions and want to ask them to help out, that might help too. :)

I can't say I am familiar with Github actions, but the docs make this seem pretty simple (

**Comment by joshua-stone** [comment]
@EinoHR You have to do a few things if you're trying to build your own images on github:

1. Generate public key and private key

The key provided by the upstream repo needs a complementary private key which is only accessible by upstream and will not be accessible in forks for security reasons:

```
$ ./generate-akmod-key
```

2. Add private key secret

Adding a secret is most easily done with the [gh](https://github.com/cli/cli#installation) utility:

```
$ gh secret set AKMOD_PRIVKEY < certs/public_key.der
```

3. Add public key to git repo

Now finally add your matching public key:

```
$ git add certs/public_key.der
$ git checkout -b pubkey
$ git commit -m "Add public key"
$ git push origin pubkey
```

And from there the github CI should be able to access your private key.



> > We're currently in the process of figuring out how to matrix out builds so that we can make one for each desktop, but it takes time.
> > Or if you know someone who's done it before and knows GitHub actions and want to ask them to help out, that might help too. :)
> 
> I can't say I am familiar with Github actions, but the docs make this seem pretty simple (https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs).
> 
> Just use strategy: matrix: to declare multiple variables. And just like you're already doing in build.yml (shown below), use the matrix vars in the build args. The BASE_IMAGE is already a build arg in the container. `build-args: | FEDORA_MAJOR_VERSION=${{ matrix.major_version }} NVIDIA_MAJOR_VERSION=${{ matrix.driver_version }}`
> 
> If you've already tried this, I'm curious, what roadblocks did you hit?
> 
> EDIT: Closed accidentally

These changes were added in an earlier PR:

https://github.com/ublue-os/nvidia/pull/22

**Comment by EinoHR** [comment]
Thanks, Joshua! I got it _mostly_ working like this. I was confused since the only mention of forking the repo in the README was under the verification header, and I didn't want to have to build locally.
But, I did have to run podman in `./generate-akmod-key` with sudo (not just randomly, but as suggested in [this issue/thread](https://github.com/containers/podman/issues/12715)), and for some reason I had to manually set the LANG variable (I got an error saying it was not declared).
Furthermore, the cosign signing step fails with another error I don't understand and which google doesn't seem to understand either, but the image still gets published to ghcr so don't know what's up with that.

I improved the documentation a bit in my fork, and I might use it as a testing ground for matrix builds.

**Comment by joshua-stone** [comment]
@EinoHR `LANG` has to be passed in order for genmodca to work:


https://github.com/ublue-os/nvidia/blob/main/generate-akmods-key#L15
https://src.fedoraproject.org/rpms/akmods/blob/rawhide/f/akmods-kmodgenca#_95

Please paste errors so we can help narrow issues.

**Comment by joshua-stone** [comment]
@EinoHR We now have building images for kinoite:

https://github.com/ublue-os/nvidia/pkgs/container/kinoite

I'm going to mark this as closed. Any further issues can be filed in a follow-up issue.

**Comment by EinoHR** [comment]
> We now have building images for kinoite

Ooh, that was quick! Thanks a lot!

> Please paste errors so we can help narrow down issues.

Here's the error I was having with `sudo ./generate-akmods-key`:
`./generate-akmods-key: line 15: LANG: unbound variable`.
An easy fix was manually declaring the lang-variable in the script like so. `readonly LANG="en_US.UTF-8"`
