### ISSUE TITLE
[Question] Does this image provide general improvement ?

### ISSUE THREAD

**Issue by valentin-cnt** [ublue-os/nvidia#82]
Hey guys, 

I've got issues lately with Nvidia drivers on Fedora Silverblue. Wayland isn't working at all and X11 is overall very slow and sloppy.
I'm curious about this image, does it add some improvements or is it just an initial configuration to support Nvidia cards from scratch ?

Cheers

**Comment by EinoHR** [comment]
It's based on ublue-os/main, and as such all of the general improvements _trickle down_. All uBlue images are based on main.

**Comment by valentin-cnt** [comment]
Ok thank you, I'm trying it then.

I have just one last question. 
On a regular Silverblue image, I installed Nvidia drivers and CUDA inside a toolbox to use them, is it still needed with the the ublue image ?

**Comment by EinoHR** [comment]
Distrobox is working on ootb nvidia support under a config option I believe, but currently I believe you still have to install the Nvidia stuff inside the container.
