### ISSUE TITLE
38-530 - breaks wayland 

### ISSUE THREAD

**Issue by breningham** [ublue-os/nvidia#84]
Not sure if this is an issue with this image or fedora-38, but using 38-530 seems to break wayland (and prevents a usable GDM/Gnome, unless you disable wayland in `/etc/gdm/custom/conf`) 

is there some extra step i might have missed going from 38-525 ?

**Comment by breningham** [comment]
also similiar (though different symptom ) in 37-530 leading me to believe that either the driver is broken, or im missing a step - will keep this open incase i have missed something, but overwise feel free to close this.

**Comment by breningham** [comment]
Update: looks like it is the driver, my display is 120Hz, potential fix here: https://www.reddit.com/r/archlinux/comments/1206ffa/is_nvidia53041031_borked_just_for_me_or_everyone/

**Comment by breningham** [comment]
Can confirm, limiting my display to 60hz allows wayland to work, while others state that they can set 120hz+ after logging in, for me that crashes the system. 

Closing this, as it is not related to this package - thanks for coming on this journey with me 😆

**Comment by castrojo** [comment]
Knowing is half the battle! Thanks for the heads up and documenting it!
